package compiler.token;

public interface IToken {
    enum TokenType {
        METVARID,
        CLASSID,
        INTLITERAL,
        CHARLITERAL,
        STRINGLITERAL,
        CLASS_WORD,
        EXTENDS_WORD,
        PUBLIC_WORD,
        STATIC_WORD,
        VOID_WORD,
        BOOLEAN_WORD,
        CHAR_WORD,
        INT_WORD,
        ABSTRACT_WORD,
        FINAL_WORD,
        IF_WORD,
        ELSE_WORD,
        WHILE_WORD,
        RETURN_WORD,
        VAR_WORD,
        THIS_WORD,
        NEW_WORD,
        NULL_WORD,
        TRUE_WORD,
        FALSE_WORD,
        OPENING_PAREN,
        CLOSING_PAREN,
        OPENING_BRACE,
        CLOSING_BRACE,
        SEMICOLON,
        COMMA,
        PERIOD,
        COLON,
        LESS_THAN,
        EQUAL_LESS_THAN,
        GREATER_THAN,
        EQUAL_GREATER_THAN,
        EXCLAMATION_POINT,
        DIFERENT,
        EQUAL,
        EQUALS_COMPARISON,
        AND,
        OR,
        PERCENT,
        PLUS,
        PLUS1,
        MINUS,
        MINUS1,
        MULTIPLY,
        SLASH,
        EOF,
    }
    TokenType getTokenType();
    String getLexeme();
    int getLineNumber();
}
